sudo: required

services:
  - docker

before_install:
  - docker build -t ccpgames/kubernetes-fluentd-s3 .

script:
  - docker tag ccpgames/kubernetes-fluentd-s3:latest ccpgames/kubernetes-fluentd-s3
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push ccpgames/kubernetes-fluentd-s3:latest
