apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-fluentd-s3-secrets
  namespace: kube-system
type: Opaque
data:
  S3_LOGS_BUCKET_NAME: dmstc2VydmljZS1jbHVzdGVyLWRldg==
  S3_LOGS_BUCKET_PREFIX: bG9ncy8=
  S3_LOGS_BUCKET_REGION: ZXUtd2VzdC0x
